apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-project
  template:
    metadata:
      labels:
        app: python-project
    spec:
      containers:
      - name: python-project
        image: devopsacr123456.azurecr.io/python-project:$(tag)
        ports:
        - containerPort: 5000
